language: node_js
node_js:
- lts/boron
- node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: D/vee6EmOu8Eg5p1aG27oanDBGK8oCBgqlqYRhH1l3Dn38ONo8k5XzCfhFwJ2vuxb+l48Ds6dWxGP/8Kzdmmy+5zQRcGPGOz+yDx4zTAi4ZDSHpHF7RYaNeoUSTNoOBuZycHuK2fvKYUT23LHLiZhGq1vUjaRDZhxCawLv+X1d8MZWhQHa21W3aTsGwdiYdwjZxcrX29KsKeG3V/I+FC+YA+Hr/jEQObIpmg4ZDLIxZ1UadTmaVjU9KcSn9RiPWr5KmYDBhVFR1lKwjO0SsCWcKdJahhIwto0G1BWrO319KtOlFwGKQ6YVG92In29r+kiBSGkOvSGHwsLSi9iuelUUlLpseF49AczTSwRkAzjv5z2DdHLCkN+/2HtMUrV4Zl+xEr9sfixmIddT8bFeA6SLWZTFOLneIc0z0QyJb3i+naxZF/MK2FypzCAPTKbSL3rqcCbNt3HgxcyfK6usYKmcpcpiyS+suXwDmpsoxELrXt6b1yU8D+tkXtME+0MGsG+L8RrMUoq+AL4qrgLu2m26YwvXLff/mxVrnyL9n2kAcz7A5olb45ie2dXnDy4xpSouVh0XSGetuLa8x29xEODzXtRh65vkfPNAkvhW8T4iehUZ9c23WICyFtujrdUmKlZp5Pf/yK53QO7+iJRTW0qDLAk2N6A0gcuge7Dn53/CU=
  file:
    - "is-whitespace-character.js"
    - "is-whitespace-character.min.js"
  on:
    tags: true
