language: node_js
node_js:
  - lts/dubnium
  - node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VBKmKGB2WOMPFnBt0YT4/qON6baNqBPCPSUqMWb868UCEe8uGVUGnaLWvNBP2HGvs1xq2TbL6pdHAaHVe+5dhTBQ90SkEFsEQcLWtXM62hpLD8pltHTwdODkiZYMPnYA0irIJ+Pm+A/sqAzuVYnTwgH1V+n67QH4u3PGLYAs5hvS9dvxhMunDiKBv3JD/a6qN8qkgCYSA+uo7HtN5fDWNHySfEvwYyuHIF5TPMmzb1QXqQV/9b5k38eJaeQI5x5LH8JiRFkFrwU5aNyR5EQeE/WdbsDSytueg8L0qXRzKFTeYW/gfvwKSCnanzTbgayfw3w+6LupwLtY2wqDTrWlpD2blBmYwC+IXiVQgYrq3KY8Be+b/zQifHVGwBFjsoRs+K5aOl76MuIEAsZwuTb5XM0rFipEBXaCBYMsrnaSi6jVW9EGTmqfM7+m1PFS6+muaB+VQaCrl6g0vW/OA/Cvao78Il4V9187HFxABbnmsv34NM3dZ7puq3GUYj/eWnf1cyEOGzRhGoaye6jHs54rb6+5Ff5qvXCJE2ScqeIz901PTJoL5eBDvrfu3ldMiMd+6+DFq8bjMtYNhsR1zCgwXEfn4BiXs5+tyHKI/1+wCS0B0Pz+VM/mUvbdckdpB1jE7t3OGDLPU6gqyDOGgJEKnIpmP2HhUFepUJQ7Bq8ADCQ=
  file:
    - 'is-whitespace-character.js'
    - 'is-whitespace-character.min.js'
  on:
    tags: true
